### ISSUE TITLE
Scala lang module is not bundled into fat jar

### ISSUE THREAD

**Issue by smiklosovic** [vert-x/mod-mysql-postgresql#65]
https://groups.google.com/forum/#!topic/vertx/BV_ce5X4CQ8

**Comment by Narigo** [comment]
I'll close this issue here and hope we can find a solution in the mailing list :)
If the suggestion there doesn't help, at least someone else might be able to say something to this. The Vert.x 2 module system became quite complex and I'm not sure whether this would be a general problem  or just a special case then...
